name: Build and Test

on: pull_request

env:
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2  
    
    # install dependencies
    - name: Download boost
      run: |
          sudo wget -O boost_1_72_0.tar.gz https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
          tar -zxvf boost_1_72_0.tar.gz
          rm boost_1_72_0.tar.gz
          cd boost_1_72_0
          ./bootstrap.sh  
          ./b2 headers
            
    - name: Set enviroment variable
      run: |
        export root=$(pwd)
        export include_dir=$root/boost_1_72_0
        echo "{BOOST_ROOT}={$root}" >> $GITHUB_ENV
        echo "{BOOST_INCLUDEDIR}={$include_dir}" >> $GITHUB_ENV
    
    - name: Create Build Environment
      run: |
        echo "BOOST_ROOT: $BOOST_ROOT"
        echo "BOOST_INCLUDEDIR: $BOOST_INCLUDEDIR"
        cmake -E make_directory ${{runner.workspace}}/build
        
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --verbose --progress
