name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  BOOST_INCLUDEDIR: NOT_FOUND
  BOOST_ROOT: NOT_FOUND

jobs:
  build-boost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install dependencies
      - name: Download boost
        run: |
            sudo wget -O boost_1_72_0.tar.gz https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
            tar -zxvf boost_1_72_0.tar.gz
            rm boost_1_72_0.tar.gz
            cd boost_1_72_0/
            export BOOST_ROOT=$(pwd)
            ./bootstrap.sh  
            ./b2 headers
          
  build-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Print enviroment Variable
      run: |
        echo "current directory: $PWD"
        echo "before boost root: $BOOST_ROOT"
        echo "BOOST_ROOT=$PWD" >> $BOOST_ROOT
        echo "after boost root: $BOOST_ROOT"
        
    #-DBOOST_ROOT=../boost -DBOOST_INCLUDEDIR=../boost/boost/include
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
