name: Build and Test

on: pull_request

env:
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2  

    - name: Check boost (2)
      run: |
        echo "BOOST_ROOT: $BOOST_ROOT"
        echo "BOOST_ROOT_1_72_0: $BOOST_ROOT_1_72_0"
        echo "BOOST_INCLUDEDIR: $BOOST_INCLUDEDIR"

    - name: Look through library!
      run: |
        ls
        cd $BOOST_ROOT_1_72_0
        ls
        cd include/
        ls
        cd boost/
        ls

    - name: Set enviroment variable
      run: |
        echo "{BOOST_ROOT}={$BOOST_ROOT_1_72_0}" >> $GITHUB_ENV
        echo "{BOOST_INCLUDEDIR}={$BOOST_ROOT_1_72_0\include\boost}" >> $GITHUB_ENV
    
    - name: Create Build Environment
      run: |
        echo "BOOST_ROOT: $BOOST_ROOT"
        echo "BOOST_INCLUDEDIR: $BOOST_INCLUDEDIR"
        cmake -E make_directory ${{runner.workspace}}/build
        
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --verbose --progress
